apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "web-app-spring-helm.fullname" . }}
  labels:
    {{- include "web-app-spring-helm.labels" . | nindent 4 }}
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "web-app-spring-helm.fullname" . }}
    weight: 100

